CREATE TABLESPACE BusDB
DATAFILE 'C:/app/data/bus.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER bus IDENTIFIED BY 12341234
DEFAULT TABLESPACE busDB;

GRANT DBA TO bus;